### ISSUE TITLE
UI polish

### ISSUE THREAD

**Issue by asg017** [datasette-io/datasette-write-ui#5]
- [ ] Row icon is mis-aligned
- [ ] Row icon tooltip gets cuts off on last row
- [ ] Description to the edit/insert modals
- [ ] clicking outside modal should close it

**Comment by simonw** [comment]
I messed around with the buttons in DevTools a bit and came up with this:

<img width="182" alt="CleanShot 2023-08-17 at 22 06 35@2x" src="https://github.com/datasette/datasette-write-ui/assets/9599/90496bd4-9b97-4377-ad98-4d5af0ed4442">

```css
.row-icon .menu button {
  display: block;
  margin-bottom: 0.3em;
  width: 100%;
}
```
And on the `div.menu`:
```css
.row-icon .menu {
  display: block;
  padding: 0.3em 0.3em 0px;
  box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 4px;
}
```
Definitely lots of room for improvement, but it's neater than what we have currently:

<img width="100" alt="CleanShot 2023-08-17 at 22 08 57@2x" src="https://github.com/datasette/datasette-write-ui/assets/9599/c8b353b1-78f9-4804-b515-ed6cac858f2c">
